/*
 * This source file was generated by the Gradle 'init' task
 */
package com.project.parser;

import org.junit.jupiter.api.Test;
import com.project.parser.App;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
