package com.project.parser;
/*
 * This source file was generated by the Gradle 'init' task
 */

import java.io.IOException;
import com.project.parser.codeparser.CodeHandler;

public class App {
    public static void main(String[] args) throws IOException {
        CodeHandler handler = new CodeHandler("D://下載/temp/spring-boot-project/asts");

        handler.parseProject("D://下載/temp/spring-boot-project/spring-boot-actuator/src/main/java",
                "spring-boot-actuator");
    }
}
